apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      containers:
      - name: datacollector
        image: 98cancro1/datacollector
        ports:
        - containerPort: 8000  # Porta Prometheus
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
