apiVersion: v1
kind: Service
metadata:
  name: datacollector
spec:
  selector:
    app: datacollector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
      name: metrics-port
  type: NodePort
