apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - name: alert-system
        image: 98cancro1/alert_system
        ports:
        - name: metrics-port
          containerPort: 8002
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
