apiVersion: v1
kind: Service
metadata:
  name: alert-system
spec:
  selector:
    app: alert-system
  ports:
    - name: prometheus  # Nome per la porta Prometheus
      protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30081  # NodePort per le metriche Prometheus
  type: NodePort
