# prova
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: command
        image: 98cancro1/server_command
        ports:
        - containerPort: 50052
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
          
      - name: query
        image: 98cancro1/server_query
        ports:
        - containerPort: 50053
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
          