apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: command
      protocol: TCP
      port: 50052
      targetPort: 50052
      nodePort: 30003
    - name: query
      protocol: TCP
      port: 50053
      targetPort: 50053
      nodePort: 30004
  type: NodePort
