apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notification-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notification-system
  template:
    metadata:
      labels:
        app: alert-notification-system
    spec:
      containers:
      - name: alert-notification-system
        image: 98cancro1/alert_notification_system
        ports:
        - containerPort: 50051
        - containerPort: 8001  # Porta per le metriche Prometheus
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"