apiVersion: v1
kind: Service
metadata:
  name: alert-notification-system
spec:
  selector:
    app: alert-notification-system
  ports:
    - protocol: TCP
      port: 8001  # Porta per le metriche Prometheus
      targetPort: 8001
      nodePort: 30082  # Porta esterna
      name: metric-port
  type: NodePort
